mode: full
query_name: PNG15_h1_1
ref_name: CHM13_v2.0
query: /projects/standard/hsiehph/gordo893/samples/PNG15b/verkko1.4.1/PNG15_ONT_HIC/assembly.haplotype1.fasta
reference: /projects/standard/hsiehph/shared/hsiehph_shared/assemblies/CHM13/T2T/v1.1/chm13.v1.1.fasta
coords_file: sample_coords_file.txt 
gene_file: 
saffire_repo_path: /users/7/javid017/AutoSafFire/

